name: Aitutaki
favicon: null
layout_spectrum: 0.4903707974590361
typography_spectrum: 0.2182889070827514
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6688145997468382
  lightness: 0.6679921336472034
  saturation: 0.935671295505017
  rhythmicContrast: 0.29485088656656444
purpose: []
